### ISSUE TITLE
Content static - data collection

### ISSUE THREAD

**Issue by nathcast** [North-Wyke-Farm-Platform/NWFP-WEB-000#18]
content/data_collection.blade.php 
This is a simple page with 2 iframes. I have added some headings and modified code so that there is not so much white space. 
If it is all ok, let me know

**Comment by GriceP** [comment]
Hi Nath... not quite sure where I need to be looking to sign off query #18, can you point me in the right direction?

**Comment by nathcast** [comment]
nothing much to do

**Comment by soilsci** [comment]
Pages ok  - cant do much with the content as Hadewij produces the tables etc.
