### ISSUE TITLE
Content Static - Facilities

### ISSUE THREAD

**Issue by nathcast** [North-Wyke-Farm-Platform/NWFP-WEB-000#28]
Page is at content/facilities.blade.php

A straightforwad page. I have moved thigs about - 
Watch-out that the link at the bottom will need to change before production to reflect out URL. 
I have found the DOIs to the 2 papers. 
If you look at the eRA datasets pages, you can see how I Have made buttons to copy and paste in clipboard and also to downlowd RIS of the papers - that was in pure PHP : i could try to do that in there. ) 
Check this dataset https://www.era.rothamsted.ac.uk/dataset/rbk1/01-YIELD852925 to see if you like that behaviour. 

N
When happy, close the issue

**Comment by soilsci** [comment]
- [ ] make folder for access and sample request document
- [ ] change wording at bottom in acknowledgement blue box

**Comment by GriceP** [comment]
Check this dataset https://www.era.rothamsted.ac.uk/dataset/rbk1/01-YIELD852925 to see if you like that behaviour.

Hi Nath and Jane.. I've checked the above link as requested.. I like the way it works
happy if issue closed
Cheers
Phil

**Comment by soilsci** [comment]
yes I like it too!
